# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            'Mike-Ward.Net'
tagline:          '.NET, Technology, Life, Whatever...'
description:      'Made by me'
url:              http://mike-ward.net
baseurl:          '/'
paginate:         10

author:
  name:           'Mike Ward'
  email:          'mike@mike-ward.net'
  url:            'https://twitter.com/mikeward_aa'

gems:
  - jekyll-sitemap

version:          '1.0.0'

github:
  repo:           'https://github.com/mike-ward'

sass:
    style:        ':compressed'

gems:
  - jekyll-seo-tag