permalink:        pretty
title:            Mike-Ward.Net
tagline:          .NET, Technology, Life, Whatever...
description:      'Mike Ward''s personal blog. Author of Markdown Edit, VSColorOutput, Tweetz, Desk Drive and more'
url:              http://mike-ward.net
author:           Mike Ward
paginate:         10
version:          '1.0.0'
highlighter:      rouge

author:
  name:           'Mike Ward'
  email:          'mike@mike-ward.net'
  url:            'https://twitter.com/mikeward_aa'
  twitter:        mikeward_aa
  github:         mike-ward
  location:       Ann Arbor, MI  USA

twitter:
  username:       mikeward_aa

author:
  twitter:        mikeward_aa

github:
  repo:           'https://github.com/mike-ward'

sass:
    style:        ':compressed'

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
