# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mike-Ward.Net
tagline:          '.NET, Technology, Life, Whatever...'
description:      'Made by me'
url:              http://mike-ward.github.io
baseurl:          '/'
paginate:         3

author:
  name:           'Mike Ward'
  url:            https://twitter.com/mikeward_aa

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mike-ward
